version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8060:8080"
    command: ["/usr/local/bin/php", "-S", "0.0.0.0:8080"]